version: "3.7"

services:
  database_event_manager:
    image: postgres
    container_name: database_event_manager
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=eventuser
      - POSTGRES_PASSWORD=eventpassword
      - POSTGRES_DB=eventmanager
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: eventmanagar
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_event_manager
    depends_on:
      - database_event_manager


volumes:
  pgdata:
    driver: local 